### ISSUE TITLE
screen turns invisible with extra options

### ISSUE THREAD

**Issue by LanEvo6** [ExOptsTeam/NFSPSExOpts#5]
after installing extra options exactly like the instructions said to, when i open the game it now shows nothing. i can see whatever is open in the background, or my desktop if it's only prostreet. i don't see any reason for it do do this. do you know why?

**Comment by berkayylmao** [comment]
#10 fixes this, please update

**Comment by nlgxzef** [comment]
Fixed with v1.0.1.2578.
