### ISSUE TITLE
PRO STREET WON'T OPEN

### ISSUE THREAD

**Issue by LuckyLuke905** [ExOptsTeam/NFSPSExOpts#6]
Please can anyone help me? I've installed the game, then when I try to open it, it goes on black screen and it return to desktop. I'm using Battery v.1.1 exe, GeneralFix and Extra Options of course. How can I solve this, what is the issue? I've installed the game in italian version (I have the disc and I've tried to play it in english but it doesn't appear from the language that I can choose) and it goes good in "vanilla" but I really want to play with this extra features! Someone can help me?

**Comment by lune1337** [comment]
having the same issue here. please help

**Comment by LuckyLuke905** [comment]
Plus the author nlgzrgn doesn't respond neither in the YouTube channel or in NFSMods website... It's a shame I really want to play it... Hope to find a solution soon!

**Comment by lune1337** [comment]
I wrote him a message on discord, hopefully he'll answer

**Comment by LuckyLuke905** [comment]
Please write me, if he respond! Hope to resolve this

**Comment by lune1337** [comment]
Alright, I have tried to fix the problem by myself and I actually did it. But I'm gonna have to put it on words after arrange it. Beacuse I tried some really random shit and it worked lol :D

**Comment by lune1337** [comment]
Actually I'm just gonna put all the game files on google drive so anyone can use it and i dont have to explain everything.

**Comment by LuckyLuke905** [comment]
Yes please!

**Comment by lune1337** [comment]
Uploading it :D it's gonna take a while, I'll be right back

**Comment by LuckyLuke905** [comment]
So will you share the link when it's finished?

**Comment by lune1337** [comment]
https://drive.google.com/file/d/1zXYFD75Sct1-VyKH0BLK-6YhVg9Z8Vqr/view?usp=sharing

Here it is. Download this, then basically replace all your root directory of NFS Prostreet with what's inside the .zip file and it should work. Run "nfs.exe" and voila. 

(if you want a shortcut to run the game, right click "nfs.exe" and click "Create shortcut". And after that drag what's created in your desktop then run the game anytime you want.)

Side note: If it doesnt work, delete everything in your NFS Prostreet directory and put the files in the .zip to the same place. 

Hope it works! Enjoy

**Comment by LuckyLuke905** [comment]
Ook, it says that I need the authorization..?

**Comment by lune1337** [comment]
sorry, forgot to make it public. try again

**Comment by LuckyLuke905** [comment]
Ook, it's starting downloading, I'll let you know if the game goes! Thanks anyway for the help!

**Comment by lune1337** [comment]
You're welcome! I hope it works

**Comment by LuckyLuke905** [comment]
I hope too!

**Comment by LuckyLuke905** [comment]
It starteeeeeed!!! Thanks man! Hope it doesn't crash ingame! Thanks a lot!

**Comment by lune1337** [comment]
Sure thing! I'm glad it worked. Have fun :]

**Comment by LuckyLuke905** [comment]
Yeah, too earlier... I'm stuck in the loading screen, either career or raceday... Don't you?

**Comment by lune1337** [comment]
It works well for me. I think you should start a new career though.

**Comment by LuckyLuke905** [comment]
Try a new save with raceday and still on loading screen...

**Comment by lune1337** [comment]
Then I guess you gotta go to your "Documents" folder and open "NFS ProStreet". It's where the save files are stored. Delete everything inside then try again. If it doesn't work, I don't know what's causing it :/

**Comment by LuckyLuke905** [comment]
Nvm, I got it worked by changing MultiFix with GenericFix. I think the problem is basically that I can't play it on my language, and it's automatically switched to english. Not a real problem though. Thanks anyway!

**Comment by lune1337** [comment]
Alrighty!

**Comment by SprkRR69** [comment]
> https://drive.google.com/file/d/1zXYFD75Sct1-VyKH0BLK-6YhVg9Z8Vqr/view?usp=sharing
> 
> Here it is. Download this, then basically replace all your root directory of NFS Prostreet with what's inside the .zip file and it should work. Run "nfs.exe" and voila.
> 
> (if you want a shortcut to run the game, right click "nfs.exe" and click "Create shortcut". And after that drag what's created in your desktop then run the game anytime you want.)
> 
> Side note: If it doesnt work, delete everything in your NFS Prostreet directory and put the files in the .zip to the same place.
> 
> Hope it works! Enjoy

Can u put in mega Google drive isn't doing it for tell me where u get them

**Comment by berkayylmao** [comment]
#10 fixes this, please update

**Comment by nlgxzef** [comment]
Fixed with v1.0.1.2578.
